### ISSUE TITLE
Error when updating settings in admin theme config

### ISSUE THREAD

**Issue by HerzScheisse** [ekdahl/webtrees-primer-theme#16]
Hey,

Dont know if its only me or this error happens for others aswell... If i want to change the seetings in the theme config, i get the following error...

webtrees v 2.1.20
primer theme v 1.0.0 (with the last 2 commits after release)

![prime theme error 1](https://github.com/user-attachments/assets/84d86186-755c-4177-8f99-dc8235825441)
![primer theme error 2](https://github.com/user-attachments/assets/7c23a763-8d2c-42bf-82c8-33b97c28c98b)

here is the error message i get:

```
SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\x93Prime...' for column `REMOVED`.`wt_session`.`session_data` at row 1 (SQL: update `wt_session` set `session_data` = initiated|b:1;_GUEST_sessiontime|s:10:"1729502142";language|s:2:"de";theme|s:23:"_webtrees-primer-theme_";last_gedcom_id|i:1;last_page_name|s:9:"index.php";last_page_parameter|s:8:"gedcom:1";last_count|i:4471;CSRF_TOKEN|s:32:"REMOVED";wt_user|i:1;flash_messages|a:1:{i:0;O:8:"stdClass":2:{s:4:"text";s:58:"The preferences for the module ?Primer? have been updated.";s:6:"status";s:7:"success";}} where `session_id` = REMOVED) …/vendor/illuminate/database/Connection.php:712
#0 …/vendor/illuminate/database/Connection.php(672): Illuminate\Database\Connection->runQueryCallback('update `wt_sess...', Array, Object(Closure))
#1 …/vendor/illuminate/database/Connection.php(514): Illuminate\Database\Connection->run('update `wt_sess...', Array, Object(Closure))
#2 …/vendor/illuminate/database/Connection.php(466): Illuminate\Database\Connection->affectingStatement('update `wt_sess...', Array)
#3 …/vendor/illuminate/database/Query/Builder.php(3062): Illuminate\Database\Connection->update('update `wt_sess...', Array)
#4 …/app/SessionDatabaseHandler.php(123): Illuminate\Database\Query\Builder->update(Array)
#5 [internal function]: Fisharebest\Webtrees\SessionDatabaseHandler->write('e501be66ee66dcb...', 'initiated|b:1;_...')
#6 …/app/Session.php(100): session_write_close()
#7 …/app/Http/Middleware/UseSession.php(80): Fisharebest\Webtrees\Session::save()
#8 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#9 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#10 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#11 …/app/Http/Middleware/UseDatabase.php(122): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#13 …/app/Http/Middleware/BadBotBlocker.php(308): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#14 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#15 …/app/Http/Middleware/CompressResponse.php(71): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#16 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#17 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#18 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#19 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#20 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#21 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#22 …/app/Http/Middleware/HandleExceptions.php(89): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#23 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#24 …/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#25 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#26 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#27 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#28 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#29 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#30 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#31 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#32 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#33 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest))
#34 …/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest), Array)
#35 …/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest()
#36 {main}
```

**Comment by ekdahl** [comment]
Hi,
I fixed the encoding of the file, can you try with the new version?

**Comment by HerzScheisse** [comment]
yep, that worked... Error is fixed now...
